version: '1'
services:
    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        - /Users/ulana/mongodbvolume/mongodb:/data/db
        - /Users/ulana/mongodbvolume/mongodb_config:/data/configdb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
    
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: pass
        ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
    
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes:
          - /Users/ulana/postgresvolume:/var/lib/postgresql/data
          - /Users/ulana/postgresçconfig:/db_config
    
    spring-backend:
        image: ipzlab3backpostgres:latest
        container_name: backend
        ports:
            - "8082:8082"
        depends_on:
            - db
            - mongo



